#!/usr/bin/env python3
"""
Continuous message generator for the Quantum MITM Detection demo.

Each chat session goes through two phases:

  Phase 1 — BB84 Channel Establishment
    Alice and Bob run Qsim.find_secure_channel() to negotiate a quantum key.
    If a hacker is present from message #1 they act as Eve, raising QBER above
    the 15 % threshold and causing the channel to be restarted repeatedly until
    QBER drops below the threshold (or max_attempts is exhausted).
    A session whose channel could never be established is recorded as 'broken'.

  Phase 2 — Encrypted Message Exchange
    Messages are encrypted with Qsim.encrypt_message(text, shared_key).
    Per-message quantum state is computed via compute_quantum_state() (seeded
    BB84 without Eve).  If a mid-session hacker intercepts, hacker_perturbation()
    (seeded BB84 with Eve) shifts the quantum state beyond the 15 % detection
    threshold, triggering a Flink alert.

AI messages:
    If ANTHROPIC_API_KEY is set, messages are generated by Claude Haiku.
    Otherwise a built-in template pool is used as fallback.

Usage:
    python generator.py [--sessions N] [--mitm-pct P] [--delay MIN MAX]
"""

import argparse
import contextlib
import io
import json
import os
import random
import signal
import sys
import threading
import time
import uuid
from datetime import datetime, timezone

import psycopg2
from kafka import KafkaProducer

# Bring Qsim into scope — it lives in the project root, one level up
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from Qsim import Qsim

from quantum import compute_quantum_state, hacker_perturbation

# ---------------------------------------------------------------------------
# Configuration defaults
# ---------------------------------------------------------------------------
KAFKA_BOOTSTRAP = "localhost:29092"
KAFKA_TOPIC     = "messages"
PG_HOST         = "localhost"
PG_PORT         = 5432
PG_DB           = "streaming"
PG_USER         = "hackathon"
PG_PASSWORD     = "hackathon"

NORMAL_NOISE_MAX     = 0.10          # max ±10 % noise on clean messages
MESSAGES_PER_SESSION = (20, 40)
BB84_NUM_BITS        = 16            # qubits for channel establishment
BB84_QBER_THRESHOLD  = 15            # percent — matches Flink detection threshold
BB84_MAX_ATTEMPTS    = 10            # retries before marking channel as 'broken'

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")

# ---------------------------------------------------------------------------
# Globals for graceful shutdown
# ---------------------------------------------------------------------------
running     = True
stats_lock  = threading.Lock()
stats       = {
    "sessions": 0,
    "messages": 0,
    "tampered_sessions": 0,
    "tampered_messages": 0,
    "broken_channels": 0,
}


def signal_handler(sig, frame):
    global running
    print("\nShutting down gracefully...")
    running = False


signal.signal(signal.SIGINT, signal_handler)


# ---------------------------------------------------------------------------
# Data helpers
# ---------------------------------------------------------------------------
def load_json(filename: str) -> list[dict]:
    path = os.path.join(DATA_DIR, filename)
    with open(path) as f:
        return json.load(f)


def _pg_connect():
    return psycopg2.connect(
        host=PG_HOST, port=PG_PORT,
        dbname=PG_DB, user=PG_USER, password=PG_PASSWORD,
    )


def seed_hackers_to_postgres(hackers: list[dict]):
    conn = _pg_connect()
    try:
        cur = conn.cursor()
        for h in hackers:
            cur.execute(
                "INSERT INTO hackers (id, name, signature_seed) "
                "VALUES (%s, %s, %s) ON CONFLICT (id) DO NOTHING",
                (h["hacker_id"], h["name"], h["signature_seed"]),
            )
        conn.commit()
        cur.close()
        print(f"Seeded {len(hackers)} hackers into Postgres.")
    finally:
        conn.close()


def insert_session_topic(
    session_id: str,
    sender_name: str,
    receiver_name: str,
    topic: str,
    message_count: int,
    channel_status: str,
):
    """Write session metadata (topic + BB84 channel status) to session_topics."""
    conn = _pg_connect()
    try:
        cur = conn.cursor()
        cur.execute(
            """
            INSERT INTO session_topics
                (session_id, sender_name, receiver_name, topic, message_count, channel_status)
            VALUES (%s, %s, %s, %s, %s, %s)
            ON CONFLICT (session_id) DO NOTHING
            """,
            (session_id, sender_name, receiver_name, topic, message_count, channel_status),
        )
        conn.commit()
        cur.close()
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Pre-built message pools — realistic conversations by topic
# Each pool has 35-40 lines; sessions draw from them in order (with wrap).
# ---------------------------------------------------------------------------
_MESSAGE_POOLS: dict[str, list[str]] = {
    "weekend plans": [
        "Hey, any plans for the weekend?",
        "Thinking of going hiking, you in?",
        "Sounds great! Which trail are you thinking?",
        "Maybe the riverside one, it's only an hour away.",
        "Perfect. What time should we meet?",
        "How about 9 am at the trailhead?",
        "Works for me! Should I bring snacks?",
        "Yes please, I'll handle the water bottles.",
        "Cool. Is the weather going to be okay?",
        "Checked the forecast — sunny all day.",
        "Amazing. I'll wear proper shoes this time.",
        "Ha, remember last time? Your sneakers were ruined.",
        "Don't remind me. Lesson learned.",
        "We should invite Sarah too, she loves hiking.",
        "Good idea, I'll text her now.",
        "Let me know what she says.",
        "She's in! Says she'll bring sandwiches.",
        "This is shaping up to be a great day.",
        "Agreed. Should we carpool to save gas?",
        "Sure, I can drive if you cover parking.",
        "Deal. See you Saturday morning then!",
        "Can't wait. It's been too long.",
        "Totally. We need to do this more often.",
        "Agreed — let's make it a monthly thing.",
        "I'm holding you to that.",
        "Same time next month, same trail?",
        "Maybe try a different one for variety.",
        "Good call. I'll research some options this week.",
        "Send me the links when you find them.",
        "Will do. Okay, see you Saturday!",
        "See you then. Get some rest Friday night.",
        "Always do. Good night!",
        "Night!",
        "Oh wait — do we need permits for that trail?",
        "Let me check… no, it's free access.",
        "Great, one less thing to worry about.",
    ],
    "work project": [
        "Hey, did you finish the report for today's meeting?",
        "Almost done, just need to add the charts.",
        "Okay, the meeting is at 3 pm, you have time.",
        "I know, I'm a bit stuck on the Q3 numbers.",
        "Want me to send you the spreadsheet?",
        "That would be super helpful, thanks.",
        "Sent. Check the second tab, the data is there.",
        "Got it, this makes much more sense now.",
        "Also, the client wants an executive summary.",
        "How long should it be? One page?",
        "Two pages max. Focus on the key wins.",
        "Got it. Should I mention the delays too?",
        "Be honest but frame it positively.",
        "Right, I'll say 'adjusted timeline' instead.",
        "Exactly. Clients appreciate transparency.",
        "Okay, draft should be ready in 30 minutes.",
        "Perfect. I'll review it before you send.",
        "Appreciate that. Fresh eyes always help.",
        "No problem, we're a team.",
        "By the way, the client rescheduled to 4 pm.",
        "Oh good, that gives me more time.",
        "Yeah, they had a conflict apparently.",
        "Okay, sending you the draft now.",
        "Reading it… this looks really solid.",
        "You think so? I was worried about the intro.",
        "The intro is great, very concise.",
        "Made a few small edits, check your email.",
        "Got the edits, they're much better.",
        "Happy to help. You ready for the call?",
        "As ready as I'll ever be.",
        "You'll do great. You know this project inside out.",
        "Thanks, that means a lot.",
        "Let me know how it goes!",
        "Will do. Fingers crossed.",
        "Good luck! Talk after the meeting.",
        "Sounds good. Chat later.",
    ],
    "food recommendations": [
        "Have you tried that new Italian place on Fifth?",
        "Not yet! Is it good?",
        "Amazing. Best carbonara I've had in years.",
        "Okay, now I have to go. What's it called?",
        "Trattoria Venezia. Little place, very cozy.",
        "Is it expensive?",
        "Pretty reasonable actually. Like 20 bucks a plate.",
        "That's not bad at all for Italian.",
        "And the wine list is excellent too.",
        "You had me at carbonara, honestly.",
        "Ha! We should go together sometime.",
        "Definitely. Do they take reservations?",
        "Yes, you pretty much need one on weekends.",
        "Good to know. What else did you try?",
        "The tiramisu was out of this world.",
        "Stop it, I'm getting hungry just reading this.",
        "Sorry not sorry.",
        "Are they open for lunch too?",
        "Yes, weekdays only though.",
        "Might try a lunch visit then.",
        "Good idea, it's less crowded at lunch.",
        "What about the pizza place on Oak Street?",
        "Honestly? Overrated. Too expensive for what it is.",
        "I thought so too but everyone raves about it.",
        "People just like the hype sometimes.",
        "Fair point. I'll skip it and try Venezia instead.",
        "You won't regret it, promise.",
        "Should I make a reservation for next Friday?",
        "Yes! 7 pm works great.",
        "Done. Looking forward to it already.",
        "Same! It's going to be a great dinner.",
        "Do they have vegetarian options?",
        "Yes, their mushroom risotto is incredible.",
        "Perfect, my sister can come then.",
        "The more the merrier!",
        "Okay, reserving for four people.",
        "See you Friday!",
    ],
    "tech news": [
        "Did you see the new chip announcement yesterday?",
        "Yes! The performance numbers are insane.",
        "40% faster than the previous generation.",
        "And apparently more power efficient too.",
        "That's the part that impressed me most.",
        "Battery life on laptops is going to improve a lot.",
        "Can't wait. My current laptop barely lasts 4 hours.",
        "Same. I'm definitely upgrading this year.",
        "When do they ship?",
        "Q3 apparently, so a few months away.",
        "Just in time for the holiday season.",
        "Coincidence? I think not.",
        "Ha, obviously timed for maximum sales.",
        "Smart business move though.",
        "True. What about the software side?",
        "The new OS update looks promising.",
        "I tried the beta, it's actually stable.",
        "Really? Betas are usually a mess.",
        "This one was surprisingly polished.",
        "Maybe they finally learned their lesson.",
        "Fingers crossed. What features stood out?",
        "The new notification system is much cleaner.",
        "The old one was cluttered, yeah.",
        "And the battery management is smarter now.",
        "That's exactly what power users needed.",
        "Agreed. I'm cautiously optimistic.",
        "Me too. Full release in September?",
        "That's what they said at the conference.",
        "I'll wait for the first patch before upgrading.",
        "Always a safe strategy.",
        "Learned that the hard way a few years back.",
        "We all have that story.",
        "What else caught your eye at the conference?",
        "The AR glasses demo was wild.",
        "I saw the clip — looked almost real.",
        "Still a few years from consumer release though.",
        "Yeah, but the direction is exciting.",
    ],
    "sports update": [
        "Did you watch the game last night?",
        "Of course! What a match.",
        "That comeback in the second half was unreal.",
        "I had basically given up by halftime.",
        "Same. Down by two and then suddenly everything clicked.",
        "The third goal was just pure brilliance.",
        "I rewatched it three times this morning.",
        "The skill level was just unbelievable.",
        "This team has really come together this season.",
        "New coach made a huge difference.",
        "Definitely. The tactics are so much sharper.",
        "And the team looks fitter too.",
        "Pre-season training paid off clearly.",
        "What did you think of the rookie?",
        "He's going to be a star, no doubt.",
        "That acceleration is something else.",
        "And he's only 20 years old.",
        "Scary to think how good he'll be in five years.",
        "If he stays healthy and keeps his head right.",
        "True, plenty of talented ones have flamed out.",
        "The pressure at this level is intense.",
        "He seems grounded though. Good family support.",
        "That always helps.",
        "Next match is Saturday, you watching?",
        "Wouldn't miss it. Big rivalry game.",
        "Should be a tough one. Away fixture too.",
        "Away form has been solid this year though.",
        "True, six wins from eight away games.",
        "That stat is really impressive.",
        "I think they can do it.",
        "I'll come over and we can watch together.",
        "Great idea. I'll get some snacks in.",
        "I'll bring the drinks.",
        "Perfect setup. Kick off at 5?",
        "Yeah, 5 pm. Come a bit early.",
        "Will do. Can't wait!",
        "It's going to be a great afternoon.",
    ],
}


def generate_session_messages(
    user_a: dict, user_b: dict, num_messages: int
) -> tuple[list[str], str]:
    """
    Pick a random topic and return num_messages lines from its pre-built pool.

    Messages are drawn in order from the pool and wrap around if the session
    is longer than the pool.  This produces coherent, realistic conversations
    without any external API dependency.
    """
    topic = random.choice(list(_MESSAGE_POOLS.keys()))
    pool  = _MESSAGE_POOLS[topic]
    # Draw in order starting from a random offset so sessions differ
    start = random.randint(0, len(pool) - 1)
    msgs  = [pool[(start + i) % len(pool)] for i in range(num_messages)]
    return msgs, topic


# ---------------------------------------------------------------------------
# Kafka producer
# ---------------------------------------------------------------------------
def create_producer() -> KafkaProducer:
    return KafkaProducer(
        bootstrap_servers=KAFKA_BOOTSTRAP,
        value_serializer=lambda v: json.dumps(v).encode("utf-8"),
        key_serializer=lambda k: k.encode("utf-8"),
    )


# ---------------------------------------------------------------------------
# Core session logic
# ---------------------------------------------------------------------------
def run_session(
    producer: KafkaProducer,
    user_a: dict,
    user_b: dict,
    hackers: list[dict],
    mitm_pct: float,
    delay: tuple[float, float],
):
    """
    Execute one complete chat session.

    Phase 1: BB84 channel establishment via Qsim.find_secure_channel().
             If a hacker is active from message #1 they act as Eve and
             repeatedly raise QBER above 15 %, forcing channel restarts.
             Session is aborted and recorded as 'broken' if no secure
             channel can be found within BB84_MAX_ATTEMPTS tries.

    Phase 2: Encrypted message exchange.  Per-message quantum state is
             computed deterministically; mid-session hacker activity shifts
             it beyond the 15 % detection threshold.
    """
    session_id   = str(uuid.uuid4())
    num_messages = random.randint(*MESSAGES_PER_SESSION)
    is_mitm      = random.random() < (mitm_pct / 100.0)
    hacker       = random.choice(hackers) if is_mitm else None
    # When does the hacker start intercepting?  Possibly from message #1.
    intercept_start = random.randint(1, num_messages) if is_mitm else num_messages + 1

    with stats_lock:
        if is_mitm:
            stats["tampered_sessions"] += 1
        stats["sessions"] += 1
        session_num = stats["sessions"]

    # -----------------------------------------------------------------------
    # Phase 1 — BB84 channel establishment
    # -----------------------------------------------------------------------
    qsim = Qsim(num_bits=BB84_NUM_BITS)
    # If the hacker is active from the very first message, they also disturb
    # the initial key exchange (Eve is active during QKD).
    initial_eve = is_mitm and intercept_start == 1

    # Suppress verbose Qsim console output
    with contextlib.redirect_stdout(io.StringIO()):
        shared_key = qsim.find_secure_channel(
            num_bits=BB84_NUM_BITS,
            eve_active=initial_eve,
            max_attempts=BB84_MAX_ATTEMPTS,
            qber_threshold=BB84_QBER_THRESHOLD,
        )

    if not shared_key:
        # Channel could never be established — record as broken and abort
        with stats_lock:
            stats["broken_channels"] += 1
        print(
            f"Session {session_num}: {user_a['name']} <-> {user_b['name']} "
            f"— BB84 FAILED (channel broken, hacker blocked key exchange)"
        )
        insert_session_topic(
            session_id, user_a["name"], user_b["name"],
            topic="channel blocked by hacker",
            message_count=0,
            channel_status="broken",
        )
        return

    # -----------------------------------------------------------------------
    # Phase 2 — Generate messages and exchange them
    # -----------------------------------------------------------------------
    messages_list, topic = generate_session_messages(user_a, user_b, num_messages)

    status = (
        f"[MITM by {hacker['name']} from msg #{intercept_start}]"
        if is_mitm else "[clean]"
    )
    print(
        f"Session {session_num}: {user_a['name']} <-> {user_b['name']} "
        f"({num_messages} msgs, topic: '{topic}') {status}"
    )

    # Record session topic and initial channel status
    insert_session_topic(
        session_id, user_a["name"], user_b["name"],
        topic=topic,
        message_count=num_messages,
        channel_status="secure",
    )

    for seq in range(1, num_messages + 1):
        if not running:
            break

        sender, receiver = (
            (user_a, user_b) if seq % 2 == 1 else (user_b, user_a)
        )

        # ------------------------------------------------------------------
        # Quantum state for this message (seeded BB84, no Eve = expected)
        # ------------------------------------------------------------------
        expected = compute_quantum_state(session_id, seq)

        is_hacker_active = is_mitm and seq >= intercept_start

        if is_hacker_active:
            # Hacker shifts the quantum state beyond 15 % threshold
            offset        = hacker_perturbation(hacker["hacker_id"], session_id, seq)
            quantum_state = expected * (1 + offset)
            with stats_lock:
                stats["tampered_messages"] += 1
        else:
            # Normal channel noise stays well below 15 %
            noise         = random.uniform(-NORMAL_NOISE_MAX, NORMAL_NOISE_MAX)
            quantum_state = expected * (1 + noise)

        # ------------------------------------------------------------------
        # Encrypt message content with the shared quantum key
        # ------------------------------------------------------------------
        plaintext        = messages_list[seq - 1]
        encrypted_content = qsim.encrypt_message(plaintext, shared_key)

        message = {
            "message_id":    str(uuid.uuid4()),
            "session_id":    session_id,
            "sender_id":     sender["user_id"],
            "sender_name":   sender["name"],
            "receiver_id":   receiver["user_id"],
            "receiver_name": receiver["name"],
            "sequence_num":  seq,
            "content":       encrypted_content,    # base64 ciphertext
            "quantum_state": round(quantum_state, 8),
            "timestamp":     datetime.now(timezone.utc).isoformat(),
        }

        producer.send(KAFKA_TOPIC, key=session_id, value=message)
        with stats_lock:
            stats["messages"] += 1

        time.sleep(random.uniform(*delay))

    producer.flush()


# ---------------------------------------------------------------------------
# Threading helpers
# ---------------------------------------------------------------------------
def session_worker(producer, users, hackers, mitm_pct, delay, semaphore):
    try:
        user_a, user_b = random.sample(users, 2)
        run_session(producer, user_a, user_b, hackers, mitm_pct, delay)
    finally:
        semaphore.release()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Quantum MITM streaming generator")
    parser.add_argument(
        "--sessions", type=int, default=10,
        help="Max concurrent active chat sessions (default: 10)",
    )
    parser.add_argument(
        "--mitm-pct", type=float, default=5.0,
        help="Percentage of sessions intercepted by a hacker (default: 5.0)",
    )
    parser.add_argument(
        "--delay", type=float, nargs=2, default=[0.5, 1.0],
        metavar=("MIN", "MAX"),
        help="Min/max delay in seconds between messages (default: 0.5 1.0)",
    )
    args = parser.parse_args()

    print("Loading data...")
    users   = load_json("users.json")
    hackers = load_json("hackers.json")
    print(f"Loaded {len(users)} users and {len(hackers)} hackers.")

    print("Seeding hackers to Postgres...")
    seed_hackers_to_postgres(hackers)

    print(f"Message generation: pre-built pools ({len(_MESSAGE_POOLS)} topics)")

    print(f"Connecting to Kafka at {KAFKA_BOOTSTRAP}...")
    producer = create_producer()
    print(
        f"Connected.  Starting: {args.sessions} concurrent sessions, "
        f"{args.mitm_pct}% MITM, delay {args.delay[0]}-{args.delay[1]}s "
        f"(Ctrl+C to stop)\n"
    )

    semaphore  = threading.Semaphore(args.sessions)
    delay_tuple = (args.delay[0], args.delay[1])

    try:
        while running:
            semaphore.acquire()
            if not running:
                semaphore.release()
                break
            t = threading.Thread(
                target=session_worker,
                args=(producer, users, hackers, args.mitm_pct, delay_tuple, semaphore),
                daemon=True,
            )
            t.start()
    finally:
        print("Waiting for active sessions to complete...")
        for _ in range(args.sessions):
            semaphore.acquire()
        producer.flush()
        producer.close()

        print("\n--- Final Stats ---")
        print(f"Sessions total:      {stats['sessions']}")
        print(f"Messages total:      {stats['messages']}")
        print(f"Tampered sessions:   {stats['tampered_sessions']}")
        print(f"Tampered messages:   {stats['tampered_messages']}")
        print(f"Broken channels:     {stats['broken_channels']}")


if __name__ == "__main__":
    main()
